# Generated by Django 3.2 on 2022-05-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorii',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-published'], 'verbose_name': 'Ogłoszenie', 'verbose_name_plural': 'Ogłoszenia'},
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='board',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='board',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas publikacji'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Produkt'),
        ),
        migrations.AddField(
            model_name='board',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Kategoria'),
        ),
    ]
